### ISSUE TITLE
custom.jmx.vegardit.ActiveMQ_Artemis_Queues plugin: ConsumerCountByQueue: missing dimension "queue"

### ISSUE THREAD

**Issue by thomas-k-git** [vegardit/activemq-artemis-dynatrace-plugin#1]
Hi!
In https://github.com/vegardit/activemq-artemis-dynatrace-plugin/blob/bf608a01e63001307c9ea088ebaab9a957075cf8/artemis-queues-plugin/custom/plugin.json

In the section
```
     "timeseries": {
        "key": "ConsumerCountByQueue",
        "unit": "Count",
        "displayname": "Consumer Count By Queue",
        "dimensions": [ "rx_pid" ]
      },
      "source": {
        "domain": "org.apache.activemq.artemis",
        "keyProperties": {
          "broker": "*",
          "component": "addresses",
          "address": "*",
          "subcomponent": "queues",
          "routing-type": "\"anycast\"",
          "queue": "*"
        },
        "attribute": "ConsumerCount",
        "allowAdditionalKeys": true,
        "calculateDelta": false,
        "calculateRate": false,
        "aggregation": "AVG",
        "splitting": {
          "name": "queue",
          "type": "keyProperty",
          "keyProperty": "queue"
        }
      }
    }
```

there is the splitting "queue" defined, but that requires also the dimension "queue" in the timeseries/dimensions element.

This causes data sent from the JMX agent sent to Dynatrace to be discarded, as there is a "dimensions mismatch" (data schema mismatch). So the data for this timeseries is lost unless the JSON is modified.

Note that newer versions of Dynatrace will validate this, causing the JSON not to be installable as is right now:
![demoDevNoUpload](https://user-images.githubusercontent.com/12692832/117293413-a0f6d300-ae71-11eb-911e-68ffb0f6d548.png)

Best regards, Thomas

**Comment by sebthom** [comment]
Thanks a lot!
