### ISSUE TITLE
Artemis Dynatrace plugin metrics not visible in Dynatrace SaaS console

### ISSUE THREAD

**Issue by ivantr5** [vegardit/activemq-artemis-dynatrace-plugin#3]
Hello,

We were trying to install ActiveMQ Artemis Dynatrace plugin (v.2.2.1635498138) in our environment and it is now already activated globally and on the host where ActiveMQ Artemis version 2.17.0 is running:

![image](https://user-images.githubusercontent.com/85614462/145569574-0389384c-c7eb-4fad-acf4-9ff6eceacffb.png)

However, when I go to process metrics, I do not see the metrics gathered by the plugin:

![image](https://user-images.githubusercontent.com/85614462/145569742-37e8236d-9449-4336-ab7c-972402a5c211.png)

I have also attached Dynatrace OneAgent logs, in case they can help in debugging the issue.

Can you please investigate what could be the problem?

Thanks,
Ivan Trpkov
[oneagent_logs.tar.gz](https://github.com/vegardit/activemq-artemis-dynatrace-plugin/files/7692441/oneagent_logs.tar.gz)

**Comment by sebthom** [comment]
The plugins get activated if Dynatrace detects the technology ActiveMQ for the running processes. See https://github.com/vegardit/activemq-artemis-dynatrace-plugin/blob/main/artemis-overview-plugin/plugin.yaml#L4

You can try to replace this ACTIVE_MQ with JAVA and see if the metrics appear.

Also see https://www.dynatrace.com/support/help/extend-dynatrace/extensions/reference/json-reference/extension-json-reference/#known-technologies-json
